### ISSUE TITLE
Contributions possible?

### ISSUE THREAD

**Issue by Raufoss** [tarkovarmory/tarkovarmory#10]
Are you generally interested in contributions?
I was looking into making a gun builder but saw that you've actually updated yours recently.
Basic additions i would consider would be stuff like showing stats/slots in the mod selection (possibly sorted) to speed up the process.

My end goal was to be able to spit out ready guns based on items (e.g. sights) and stats (silenced, budget, etc) but that may be excessive depending on how well other things work.

**Comment by tarkovarmory** [comment]
Sure that sounds awesome
